version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:us-east-1:982590066260:task-definition/blacklist-v2:1
        LoadBalancerInfo:
          ContainerName: blacklist-container
          ContainerPort: 8080